# Generated by Django 6.0.2 on 2026-02-13 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('undergrad_degree', models.CharField(blank=True, max_length=200, null=True)),
                ('undergrad_cgpa', models.CharField(blank=True, max_length=20, null=True)),
                ('grade_12_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('grade_10_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('ielts_toefl_score', models.CharField(blank=True, max_length=20, null=True)),
                ('gre_score', models.CharField(blank=True, max_length=20, null=True)),
                ('gmat_score', models.CharField(blank=True, max_length=20, null=True)),
                ('work_experience_years', models.IntegerField(blank=True, default=0, null=True)),
                ('funds_available', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_countries', models.TextField(blank=True, null=True)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
