# Generated by Django 6.0.2 on 2026-03-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('course_field', models.CharField(max_length=100)),
                ('degree_level', models.CharField(max_length=100)),
                ('min_ielts', models.FloatField(default=0.0)),
                ('min_german_score', models.FloatField(default=0.0)),
                ('min_academic_percentage', models.FloatField(default=0.0)),
                ('tuition_fee_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('backlogs_allowed', models.IntegerField(default=0)),
                ('work_experience_required', models.IntegerField(default=0)),
                ('intake', models.CharField(max_length=100)),
                ('ranking_tier', models.CharField(max_length=50)),
            ],
        ),
    ]
